[workspace.dependencies]
mcdata = { path = "../mcdata" }

[package]
name = "rustmatica"
version = "0.5.2"
authors = ["RubixDev"]
categories = ["encoding", "wasm"]
edition = "2021"
exclude = [".github", "dprint.json", "test_files"]
keywords = ["minecraft", "serde", "litematic", "litematica", "nbt"]
license = "GPL-3.0-only"
repository = "https://github.com/RubixDev/rustmatica"
description = "A Rust library for reading, editing, and writing Minecraft litematic files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
#! ## Features
default = ["chrono", "image"]

## Use [`chrono`] types for timestamps.
chrono = ["dep:chrono"]

## Use the [`image`] crate for preview images.
image = ["dep:image"]

## Enable this when building the docs
docs = ["dep:document-features", "dep:rustc_version"]

_mcdata-all = ["mcdata/entities", "mcdata/block-entities", "mcdata/mc-all"]

[dependencies]
document-features = { version = "0.2", optional = true }
#simdnbt = "0.9"
fastnbt = "2.6"
flate2 = "1.1"
image = { version = "0.25", optional = true }
mcdata.workspace = true
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
chrono = { version = "0.4", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
chrono = { version = "0.4", features = ["wasmbind"], optional = true }
js-sys = "0.3" # for current time without chrono feature

[dev-dependencies]
bounded-integer = "0.6"
mcdata = { workspace = true, features = ["latest", "block-states"] }
serde_json = "1.0"
viuer = "0.11"
zip = { version = "7.0", default-features = false, features = ["deflate"] }

[build-dependencies]
rustc_version = { version = "0.4.1", optional = true }

[package.metadata.docs.rs]
all-features = true
